export const fallbackCountries = [
  {
    name: { common: "Argentina" },
    cca2: "AR",
    flags: { svg: "https://flagcdn.com/ar.svg", png: "https://flagcdn.com/w320/ar.png" },
    capital: ["Buenos Aires"],
    region: "Americas",
    subregion: "South America",
    currencies: { ARS: { name: "Argentine peso" } },
    languages: { spa: "Spanish" },
  },
  {
    name: { common: "Brazil" },
    cca2: "BR",
    flags: { svg: "https://flagcdn.com/br.svg", png: "https://flagcdn.com/w320/br.png" },
    capital: ["Brasília"],
    region: "Americas",
    subregion: "South America",
    currencies: { BRL: { name: "Brazilian real" } },
    languages: { por: "Portuguese" },
  },
  {
    name: { common: "Canada" },
    cca2: "CA",
    flags: { svg: "https://flagcdn.com/ca.svg", png: "https://flagcdn.com/w320/ca.png" },
    capital: ["Ottawa"],
    region: "Americas",
    subregion: "North America",
    currencies: { CAD: { name: "Canadian dollar" } },
    languages: { eng: "English", fra: "French" },
  },
  {
    name: { common: "Chile" },
    cca2: "CL",
    flags: { svg: "https://flagcdn.com/cl.svg", png: "https://flagcdn.com/w320/cl.png" },
    capital: ["Santiago"],
    region: "Americas",
    subregion: "South America",
    currencies: { CLP: { name: "Chilean peso" } },
    languages: { spa: "Spanish" },
  },
  {
    name: { common: "Colombia" },
    cca2: "CO",
    flags: { svg: "https://flagcdn.com/co.svg", png: "https://flagcdn.com/w320/co.png" },
    capital: ["Bogotá"],
    region: "Americas",
    subregion: "South America",
    currencies: { COP: { name: "Colombian peso" } },
    languages: { spa: "Spanish" },
  },
  {
    name: { common: "Egypt" },
    cca2: "EG",
    flags: { svg: "https://flagcdn.com/eg.svg", png: "https://flagcdn.com/w320/eg.png" },
    capital: ["Cairo"],
    region: "Africa",
    subregion: "Northern Africa",
    currencies: { EGP: { name: "Egyptian pound" } },
    languages: { ara: "Arabic" },
  },
  {
    name: { common: "France" },
    cca2: "FR",
    flags: { svg: "https://flagcdn.com/fr.svg", png: "https://flagcdn.com/w320/fr.png" },
    capital: ["Paris"],
    region: "Europe",
    subregion: "Western Europe",
    currencies: { EUR: { name: "Euro" } },
    languages: { fra: "French" },
  },
  {
    name: { common: "Germany" },
    cca2: "DE",
    flags: { svg: "https://flagcdn.com/de.svg", png: "https://flagcdn.com/w320/de.png" },
    capital: ["Berlin"],
    region: "Europe",
    subregion: "Western Europe",
    currencies: { EUR: { name: "Euro" } },
    languages: { deu: "German" },
  },
  {
    name: { common: "India" },
    cca2: "IN",
    flags: { svg: "https://flagcdn.com/in.svg", png: "https://flagcdn.com/w320/in.png" },
    capital: ["New Delhi"],
    region: "Asia",
    subregion: "Southern Asia",
    currencies: { INR: { name: "Indian rupee" } },
    languages: { hin: "Hindi", eng: "English" },
  },
  {
    name: { common: "Italy" },
    cca2: "IT",
    flags: { svg: "https://flagcdn.com/it.svg", png: "https://flagcdn.com/w320/it.png" },
    capital: ["Rome"],
    region: "Europe",
    subregion: "Southern Europe",
    currencies: { EUR: { name: "Euro" } },
    languages: { ita: "Italian" },
  },
  {
    name: { common: "Japan" },
    cca2: "JP",
    flags: { svg: "https://flagcdn.com/jp.svg", png: "https://flagcdn.com/w320/jp.png" },
    capital: ["Tokyo"],
    region: "Asia",
    subregion: "Eastern Asia",
    currencies: { JPY: { name: "Japanese yen" } },
    languages: { jpn: "Japanese" },
  },
  {
    name: { common: "Mexico" },
    cca2: "MX",
    flags: { svg: "https://flagcdn.com/mx.svg", png: "https://flagcdn.com/w320/mx.png" },
    capital: ["Mexico City"],
    region: "Americas",
    subregion: "North America",
    currencies: { MXN: { name: "Mexican peso" } },
    languages: { spa: "Spanish" },
  },
  {
    name: { common: "Morocco" },
    cca2: "MA",
    flags: { svg: "https://flagcdn.com/ma.svg", png: "https://flagcdn.com/w320/ma.png" },
    capital: ["Rabat"],
    region: "Africa",
    subregion: "Northern Africa",
    currencies: { MAD: { name: "Moroccan dirham" } },
    languages: { ara: "Arabic", ber: "Berber" },
  },
  {
    name: { common: "Nigeria" },
    cca2: "NG",
    flags: { svg: "https://flagcdn.com/ng.svg", png: "https://flagcdn.com/w320/ng.png" },
    capital: ["Abuja"],
    region: "Africa",
    subregion: "Western Africa",
    currencies: { NGN: { name: "Nigerian naira" } },
    languages: { eng: "English" },
  },
  {
    name: { common: "Peru" },
    cca2: "PE",
    flags: { svg: "https://flagcdn.com/pe.svg", png: "https://flagcdn.com/w320/pe.png" },
    capital: ["Lima"],
    region: "Americas",
    subregion: "South America",
    currencies: { PEN: { name: "Peruvian sol" } },
    languages: { spa: "Spanish" },
  },
  {
    name: { common: "South Africa" },
    cca2: "ZA",
    flags: { svg: "https://flagcdn.com/za.svg", png: "https://flagcdn.com/w320/za.png" },
    capital: ["Pretoria"],
    region: "Africa",
    subregion: "Southern Africa",
    currencies: { ZAR: { name: "South African rand" } },
    languages: { eng: "English", afr: "Afrikaans" },
  },
  {
    name: { common: "South Korea" },
    cca2: "KR",
    flags: { svg: "https://flagcdn.com/kr.svg", png: "https://flagcdn.com/w320/kr.png" },
    capital: ["Seoul"],
    region: "Asia",
    subregion: "Eastern Asia",
    currencies: { KRW: { name: "South Korean won" } },
    languages: { kor: "Korean" },
  },
  {
    name: { common: "Spain" },
    cca2: "ES",
    flags: { svg: "https://flagcdn.com/es.svg", png: "https://flagcdn.com/w320/es.png" },
    capital: ["Madrid"],
    region: "Europe",
    subregion: "Southern Europe",
    currencies: { EUR: { name: "Euro" } },
    languages: { spa: "Spanish" },
  },
  {
    name: { common: "United Kingdom" },
    cca2: "GB",
    flags: { svg: "https://flagcdn.com/gb.svg", png: "https://flagcdn.com/w320/gb.png" },
    capital: ["London"],
    region: "Europe",
    subregion: "Northern Europe",
    currencies: { GBP: { name: "British pound" } },
    languages: { eng: "English" },
  },
  {
    name: { common: "United States" },
    cca2: "US",
    flags: { svg: "https://flagcdn.com/us.svg", png: "https://flagcdn.com/w320/us.png" },
    capital: ["Washington, D.C."],
    region: "Americas",
    subregion: "North America",
    currencies: { USD: { name: "United States dollar" } },
    languages: { eng: "English" },
  },
];
